"""empty message

Revision ID: 0211328588b5
Revises: e74f03cf06f6
Create Date: 2020-01-20 22:50:01.383689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0211328588b5'
down_revision = 'e74f03cf06f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('website_priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'website_priority')
    # ### end Alembic commands ###
