"""empty message

Revision ID: 0c3a0aee0167
Revises: abf8032ff5a8
Create Date: 2021-12-05 19:42:08.949532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c3a0aee0167'
down_revision = 'abf8032ff5a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bids', sa.Column('company_user_id', sa.Integer(), nullable=True))
    op.drop_index('ix_bids_company_id', table_name='bids')
    op.create_index(op.f('ix_bids_company_user_id'), 'bids', ['company_user_id'], unique=False)
    op.drop_constraint('bids_company_id_fkey', 'bids', type_='foreignkey')
    op.create_foreign_key(None, 'bids', 'company_users', ['company_user_id'], ['id'])
    op.drop_column('bids', 'company_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bids', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bids', type_='foreignkey')
    op.create_foreign_key('bids_company_id_fkey', 'bids', 'companies', ['company_id'], ['id'])
    op.drop_index(op.f('ix_bids_company_user_id'), table_name='bids')
    op.create_index('ix_bids_company_id', 'bids', ['company_id'], unique=False)
    op.drop_column('bids', 'company_user_id')
    # ### end Alembic commands ###
