"""empty message

Revision ID: 1e4a77df615a
Revises: 9ba22b869766
Create Date: 2021-11-15 22:51:33.447724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e4a77df615a'
down_revision = '9ba22b869766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('starting_time', sa.String(length=10), nullable=True))
    op.add_column('auctions', sa.Column('closing_time', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auctions', 'closing_time')
    op.drop_column('auctions', 'starting_time')
    # ### end Alembic commands ###
