"""empty message

Revision ID: 1e97ba034681
Revises: 8de8ba3940b8
Create Date: 2019-09-05 19:26:46.504189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e97ba034681'
down_revision = '8de8ba3940b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('colaborators_ist_id_key', 'colaborators', type_='unique')
    op.add_column('companies', sa.Column('partnership_tier', sa.String(length=20), nullable=True))
    op.drop_column('companies', 'tier')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('tier', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('companies', 'partnership_tier')
    op.create_unique_constraint('colaborators_ist_id_key', 'colaborators', ['ist_id'])
    # ### end Alembic commands ###
