"""empty message

Revision ID: 29cba7a09d15
Revises: 766f4c41f043
Create Date: 2020-02-27 20:48:55.525215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29cba7a09d15'
down_revision = '766f4c41f043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('food_manager', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'food_manager')
    # ### end Alembic commands ###
