
"""empty message

Revision ID: 3c6259f8bca9
Revises: b2bbd9568c45
Create Date: 2019-11-04 17:10:36.406900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '3c6259f8bca9'
down_revision = 'b2bbd9568c45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auctions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('external_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('minimum_value', sa.Float(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auctions_external_id'), 'auctions', ['external_id'], unique=False)
    op.create_table('bids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('external_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('auction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bids_company_id'), 'bids', ['company_id'], unique=False)
    op.create_index(op.f('ix_bids_external_id'), 'bids', ['external_id'], unique=False)
    op.create_table('company_auctions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('external_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('auction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_auctions_auction_id'), 'company_auctions', ['auction_id'], unique=False)
    op.create_index(op.f('ix_company_auctions_company_id'), 'company_auctions', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_auctions_external_id'), 'company_auctions', ['external_id'], unique=False)
    op.drop_constraint('companies_user_id_fkey', 'companies', type_='foreignkey')
    op.drop_column('companies', 'user_id')
    op.drop_column('companies', 'password_hash')
    op.add_column('users', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_auth_email_destination', sa.String(), nullable=True))
    op.add_column('users', sa.Column('sent_authentication_to_email', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'sent_authentication_to_email')
    op.drop_column('users', 'last_auth_email_destination')
    op.drop_column('users', 'email')
    op.drop_column('users', 'company_id')
    op.add_column('companies', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('companies_user_id_fkey', 'companies', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_company_auctions_external_id'), table_name='company_auctions')
    op.drop_index(op.f('ix_company_auctions_company_id'), table_name='company_auctions')
    op.drop_index(op.f('ix_company_auctions_auction_id'), table_name='company_auctions')
    op.drop_table('company_auctions')
    op.drop_index(op.f('ix_bids_external_id'), table_name='bids')
    op.drop_index(op.f('ix_bids_company_id'), table_name='bids')
    op.drop_table('bids')
    op.drop_index(op.f('ix_auctions_external_id'), table_name='auctions')
    op.drop_table('auctions')
    # ### end Alembic commands ###
