"""empty message

Revision ID: 45fb972f08ad
Revises: 3c07a1bd79a8
Create Date: 2019-11-06 19:45:08.293986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45fb972f08ad'
down_revision = '3c07a1bd79a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('accepted_terms', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'accepted_terms')
    # ### end Alembic commands ###
