"""empty message

Revision ID: 766f4c41f043
Revises: 24becb3f405d
Create Date: 2020-02-22 14:48:47.635680

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '766f4c41f043'
down_revision = '24becb3f405d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_event_information_external_id', table_name='event_information')
    op.drop_table('event_information')
    op.add_column('activities', sa.Column('activity_type_id', sa.Integer(), nullable=True))
    op.add_column('activities', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'activities', 'activity_types', ['activity_type_id'], ['id'])
    op.create_foreign_key(None, 'activities', 'events', ['event_id'], ['id'])
    op.drop_column('activities', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('type', postgresql.ENUM('workshop', 'presentation', 'tech_talk', 'job_fair', 'matchmaking', 'panel_discussion', name='activitytypeenum'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_column('activities', 'event_id')
    op.drop_column('activities', 'activity_type_id')
    op.create_table('event_information',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('external_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('date', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('facebook_link', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('youtube_link', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('instagram_link', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='event_information_pkey'),
    sa.UniqueConstraint('name', name='event_information_name_key')
    )
    op.create_index('ix_event_information_external_id', 'event_information', ['external_id'], unique=False)
    # ### end Alembic commands ###
