"""empty message

Revision ID: 7fa40673d0c3
Revises: b23e5eef0670
Create Date: 2019-09-15 01:18:50.143303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fa40673d0c3'
down_revision = 'b23e5eef0670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speakers', sa.Column('company_link', sa.String(length=100), nullable=True))
    op.add_column('speakers', sa.Column('spotlight', sa.Boolean(), nullable=True))
    op.add_column('speakers', sa.Column('website_url', sa.String(length=100), nullable=True))
    op.add_column('speakers', sa.Column('youtube_url', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('speakers', 'youtube_url')
    op.drop_column('speakers', 'website_url')
    op.drop_column('speakers', 'spotlight')
    op.drop_column('speakers', 'company_link')
    # ### end Alembic commands ###
