"""empty message

Revision ID: 884697231ba1
Revises: b0a31b6f6527
Create Date: 2022-03-20 01:13:31.791980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "884697231ba1"
down_revision = "b0a31b6f6527"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "student_activities", "company_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "student_activities", "company_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
