"""empty message

Revision ID: 97189ba55261
Revises: 2f58fc66cf0b
Create Date: 2020-12-28 23:13:07.656589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97189ba55261'
down_revision = '2f58fc66cf0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('points', sa.Integer(), nullable=True))
    op.add_column('activities', sa.Column('quest', sa.Boolean(), nullable=True))
    op.alter_column('activities', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_index('ix_activities_external_id', table_name='activities')
    op.create_index(op.f('ix_activities_external_id'), 'activities', ['external_id'], unique=True)
    op.add_column('activity_types', sa.Column('show_in_app', sa.Boolean(), nullable=True))
    op.add_column('activity_types', sa.Column('show_in_home', sa.Boolean(), nullable=True))
    op.add_column('activity_types', sa.Column('show_in_schedule', sa.Boolean(), nullable=True))
    op.drop_index('ix_activity_types_external_id', table_name='activity_types')
    op.create_index(op.f('ix_activity_types_external_id'), 'activity_types', ['external_id'], unique=True)
    op.drop_index('ix_auctions_external_id', table_name='auctions')
    op.create_index(op.f('ix_auctions_external_id'), 'auctions', ['external_id'], unique=True)
    op.drop_index('ix_bids_external_id', table_name='bids')
    op.create_index(op.f('ix_bids_external_id'), 'bids', ['external_id'], unique=True)
    op.drop_index('ix_colaborators_external_id', table_name='colaborators')
    op.create_index(op.f('ix_colaborators_external_id'), 'colaborators', ['external_id'], unique=True)
    op.drop_index('ix_companies_external_id', table_name='companies')
    op.create_index(op.f('ix_companies_external_id'), 'companies', ['external_id'], unique=True)
    op.drop_index('ix_company_activities_external_id', table_name='company_activities')
    op.create_index(op.f('ix_company_activities_external_id'), 'company_activities', ['external_id'], unique=True)
    op.drop_index('ix_company_auctions_external_id', table_name='company_auctions')
    op.create_index(op.f('ix_company_auctions_external_id'), 'company_auctions', ['external_id'], unique=True)
    op.drop_index('ix_company_dishes_external_id', table_name='company_dishes')
    op.create_index(op.f('ix_company_dishes_external_id'), 'company_dishes', ['external_id'], unique=True)
    op.drop_index('ix_company_meals_external_id', table_name='company_meals')
    op.create_index(op.f('ix_company_meals_external_id'), 'company_meals', ['external_id'], unique=True)
    op.drop_index('ix_company_resume_submissions_external_id', table_name='company_resume_submissions')
    op.create_index(op.f('ix_company_resume_submissions_external_id'), 'company_resume_submissions', ['external_id'], unique=True)
    op.drop_index('ix_dishes_external_id', table_name='dishes')
    op.create_index(op.f('ix_dishes_external_id'), 'dishes', ['external_id'], unique=True)
    op.add_column('events', sa.Column('show_registrations', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('show_schedule', sa.Boolean(), nullable=True))
    op.drop_index('ix_events_external_id', table_name='events')
    op.create_index(op.f('ix_events_external_id'), 'events', ['external_id'], unique=True)
    op.drop_index('ix_meals_external_id', table_name='meals')
    op.create_index(op.f('ix_meals_external_id'), 'meals', ['external_id'], unique=True)
    op.drop_index('ix_resume_submissions_external_id', table_name='resume_submissions')
    op.create_index(op.f('ix_resume_submissions_external_id'), 'resume_submissions', ['external_id'], unique=True)
    op.drop_index('ix_speaker_activities_external_id', table_name='speaker_activities')
    op.create_index(op.f('ix_speaker_activities_external_id'), 'speaker_activities', ['external_id'], unique=True)
    op.drop_index('ix_speakers_external_id', table_name='speakers')
    op.create_index(op.f('ix_speakers_external_id'), 'speakers', ['external_id'], unique=True)
    op.drop_index('ix_student_companies_external_id', table_name='student_companies')
    op.create_index(op.f('ix_student_companies_external_id'), 'student_companies', ['external_id'], unique=True)
    op.add_column('students', sa.Column('daily_points', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('fenix_auth_code', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('level_id', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('linkedin_url', sa.String(length=150), nullable=True))
    op.add_column('students', sa.Column('photo', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('photo_type', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('squad_id', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('squad_points', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('total_points', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('uploaded_cv', sa.Boolean(), nullable=True))
    op.alter_column('students', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_index(op.f('ix_students_fenix_auth_code'), 'students', ['fenix_auth_code'], unique=True)
    op.create_index(op.f('ix_students_ist_id'), 'students', ['ist_id'], unique=True)
    op.drop_index('ix_students_external_id', table_name='students')
    op.create_index(op.f('ix_students_external_id'), 'students', ['external_id'], unique=True)
    op.drop_constraint('students_ist_id_key', 'students', type_='unique')
    op.create_foreign_key(None, 'students', 'levels', ['level_id'], ['id'])
    op.create_foreign_key(None, 'students', 'squads', ['squad_id'], ['id'], ondelete='SET NULL')
    op.drop_column('students', 'accepted_terms')
    op.add_column('teams', sa.Column('event_id', sa.Integer(), nullable=True))
    op.drop_index('ix_teams_external_id', table_name='teams')
    op.create_index(op.f('ix_teams_external_id'), 'teams', ['external_id'], unique=True)
    op.create_foreign_key(None, 'teams', 'events', ['event_id'], ['id'])
    op.drop_index('ix_users_external_id', table_name='users')
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.create_index('ix_users_external_id', 'users', ['external_id'], unique=False)
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_index(op.f('ix_teams_external_id'), table_name='teams')
    op.create_index('ix_teams_external_id', 'teams', ['external_id'], unique=False)
    op.drop_column('teams', 'event_id')
    op.add_column('students', sa.Column('accepted_terms', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_unique_constraint('students_ist_id_key', 'students', ['ist_id'])
    op.drop_index(op.f('ix_students_external_id'), table_name='students')
    op.create_index('ix_students_external_id', 'students', ['external_id'], unique=False)
    op.drop_index(op.f('ix_students_ist_id'), table_name='students')
    op.drop_index(op.f('ix_students_fenix_auth_code'), table_name='students')
    op.alter_column('students', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('students', 'uploaded_cv')
    op.drop_column('students', 'total_points')
    op.drop_column('students', 'squad_points')
    op.drop_column('students', 'squad_id')
    op.drop_column('students', 'photo_type')
    op.drop_column('students', 'photo')
    op.drop_column('students', 'linkedin_url')
    op.drop_column('students', 'level_id')
    op.drop_column('students', 'fenix_auth_code')
    op.drop_column('students', 'daily_points')
    op.drop_index(op.f('ix_student_companies_external_id'), table_name='student_companies')
    op.create_index('ix_student_companies_external_id', 'student_companies', ['external_id'], unique=False)
    op.drop_index(op.f('ix_speakers_external_id'), table_name='speakers')
    op.create_index('ix_speakers_external_id', 'speakers', ['external_id'], unique=False)
    op.drop_index(op.f('ix_speaker_activities_external_id'), table_name='speaker_activities')
    op.create_index('ix_speaker_activities_external_id', 'speaker_activities', ['external_id'], unique=False)
    op.drop_index(op.f('ix_resume_submissions_external_id'), table_name='resume_submissions')
    op.create_index('ix_resume_submissions_external_id', 'resume_submissions', ['external_id'], unique=False)
    op.drop_index(op.f('ix_meals_external_id'), table_name='meals')
    op.create_index('ix_meals_external_id', 'meals', ['external_id'], unique=False)
    op.drop_index(op.f('ix_events_external_id'), table_name='events')
    op.create_index('ix_events_external_id', 'events', ['external_id'], unique=False)
    op.drop_column('events', 'show_schedule')
    op.drop_column('events', 'show_registrations')
    op.drop_index(op.f('ix_dishes_external_id'), table_name='dishes')
    op.create_index('ix_dishes_external_id', 'dishes', ['external_id'], unique=False)
    op.drop_index(op.f('ix_company_resume_submissions_external_id'), table_name='company_resume_submissions')
    op.create_index('ix_company_resume_submissions_external_id', 'company_resume_submissions', ['external_id'], unique=False)
    op.drop_index(op.f('ix_company_meals_external_id'), table_name='company_meals')
    op.create_index('ix_company_meals_external_id', 'company_meals', ['external_id'], unique=False)
    op.drop_index(op.f('ix_company_dishes_external_id'), table_name='company_dishes')
    op.create_index('ix_company_dishes_external_id', 'company_dishes', ['external_id'], unique=False)
    op.drop_index(op.f('ix_company_auctions_external_id'), table_name='company_auctions')
    op.create_index('ix_company_auctions_external_id', 'company_auctions', ['external_id'], unique=False)
    op.drop_index(op.f('ix_company_activities_external_id'), table_name='company_activities')
    op.create_index('ix_company_activities_external_id', 'company_activities', ['external_id'], unique=False)
    op.drop_index(op.f('ix_companies_external_id'), table_name='companies')
    op.create_index('ix_companies_external_id', 'companies', ['external_id'], unique=False)
    op.drop_index(op.f('ix_colaborators_external_id'), table_name='colaborators')
    op.create_index('ix_colaborators_external_id', 'colaborators', ['external_id'], unique=False)
    op.drop_index(op.f('ix_bids_external_id'), table_name='bids')
    op.create_index('ix_bids_external_id', 'bids', ['external_id'], unique=False)
    op.drop_index(op.f('ix_auctions_external_id'), table_name='auctions')
    op.create_index('ix_auctions_external_id', 'auctions', ['external_id'], unique=False)
    op.drop_index(op.f('ix_activity_types_external_id'), table_name='activity_types')
    op.create_index('ix_activity_types_external_id', 'activity_types', ['external_id'], unique=False)
    op.drop_column('activity_types', 'show_in_schedule')
    op.drop_column('activity_types', 'show_in_home')
    op.drop_column('activity_types', 'show_in_app')
    op.drop_index(op.f('ix_activities_external_id'), table_name='activities')
    op.create_index('ix_activities_external_id', 'activities', ['external_id'], unique=False)
    op.alter_column('activities', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('activities', 'quest')
    op.drop_column('activities', 'points')
    # ### end Alembic commands ###
