"""empty message

Revision ID: 9ba22b869766
Revises: 4c818dabbb3f
Create Date: 2021-11-15 22:09:41.393204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba22b869766'
down_revision = '4c818dabbb3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auctions', 'is_open')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('is_open', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
