"""empty message

Revision ID: 9bc3390ef3f7
Revises: 38a73cdef9b5
Create Date: 2022-02-20 00:27:03.999950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc3390ef3f7'
down_revision = '38a73cdef9b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('colaborators_name_key', 'colaborators', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('colaborators_name_key', 'colaborators', ['name'])
    # ### end Alembic commands ###
