"""empty message

Revision ID: abf8032ff5a8
Revises: 
Create Date: 2021-12-04 19:56:57.237623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abf8032ff5a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('starting_date', sa.String(length=200), nullable=True))
    op.add_column('auctions', sa.Column('starting_time', sa.String(length=10), nullable=True))
    op.add_column('auctions', sa.Column('closing_time', sa.String(length=10), nullable=True))
    op.drop_column('auctions', 'is_open')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('is_open', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('auctions', 'closing_time')
    op.drop_column('auctions', 'starting_time')
    op.drop_column('auctions', 'starting_date')
    # ### end Alembic commands ###
