"""empty message

Revision ID: b23e5eef0670
Revises: 1e97ba034681
Create Date: 2019-09-11 00:01:38.846762

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b23e5eef0670'
down_revision = '1e97ba034681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('day', sa.String(length=20), nullable=True))
    op.add_column('activities', sa.Column('time', sa.String(length=10), nullable=True))
    op.drop_constraint('activities_company_id_fkey', 'activities', type_='foreignkey')
    op.drop_constraint('activities_speaker_id_fkey', 'activities', type_='foreignkey')
    op.drop_column('activities', 'company_id')
    op.drop_column('activities', 'speaker_id')
    op.drop_column('activities', 'datetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('speaker_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('activities_speaker_id_fkey', 'activities', 'speakers', ['speaker_id'], ['id'])
    op.create_foreign_key('activities_company_id_fkey', 'activities', 'companies', ['company_id'], ['id'])
    op.drop_column('activities', 'time')
    op.drop_column('activities', 'day')
    # ### end Alembic commands ###
