"""empty message

Revision ID: b2bbd9568c45
Revises: 7842f1c6a2f1
Create Date: 2019-10-19 23:03:06.489372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2bbd9568c45'
down_revision = '7842f1c6a2f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('show_in_website', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'show_in_website')
    # ### end Alembic commands ###
