"""empty message

Revision ID: b897e2ac23fb
Revises: 
Create Date: 2022-03-13 22:56:19.916404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b897e2ac23fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('code_work_flow', sa.Enum('AdminOneUseCode', 'AdminMultiUseCode', 'CompanyOneUseCode', 'CompanyMultiUseCode', 'CompanyISTID', name='codeflowenum'), nullable=True))
    op.drop_column('companies', 'evf_password')
    op.drop_column('companies', 'evf_username')
    op.drop_column('company_activities', 'zoom_link')
    op.drop_column('company_users', 'evf_password')
    op.drop_column('company_users', 'evf_username')
    op.add_column('events', sa.Column('show_prizes', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('end_game_day', sa.String(length=20), nullable=True))
    op.add_column('events', sa.Column('end_game_time', sa.String(length=10), nullable=True))
    op.add_column('jeecpot_rewards', sa.Column('cv_platform_raffle_reward_id', sa.Integer(), nullable=True))
    op.add_column('jeecpot_rewards', sa.Column('cv_platform_raffle_winner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jeecpot_rewards', 'rewards', ['cv_platform_raffle_reward_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'jeecpot_rewards', 'students', ['cv_platform_raffle_winner_id'], ['id'], ondelete='SET NULL')
    op.add_column('student_activities', sa.Column('code', sa.String(length=16), nullable=False))
    op.create_unique_constraint('uix_student_activities', 'student_activities', ['student_id', 'activity_id'])
    op.add_column('student_referrals', sa.Column('code', sa.String(length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_referrals', 'code')
    op.drop_constraint('uix_student_activities', 'student_activities', type_='unique')
    op.drop_column('student_activities', 'code')
    op.drop_constraint(None, 'jeecpot_rewards', type_='foreignkey')
    op.drop_constraint(None, 'jeecpot_rewards', type_='foreignkey')
    op.drop_column('jeecpot_rewards', 'cv_platform_raffle_winner_id')
    op.drop_column('jeecpot_rewards', 'cv_platform_raffle_reward_id')
    op.drop_column('events', 'end_game_time')
    op.drop_column('events', 'end_game_day')
    op.drop_column('events', 'show_prizes')
    op.add_column('company_users', sa.Column('evf_username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('company_users', sa.Column('evf_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('company_activities', sa.Column('zoom_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('evf_username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('evf_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('activities', 'code_work_flow')
    # ### end Alembic commands ###
