"""empty message

Revision ID: ca79dc5d520a
Revises: f26c97884a83
Create Date: 2022-03-06 20:39:18.284012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ca79dc5d520a"
down_revision = "f26c97884a83"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activities",
        sa.Column(
            "code_work_flow",
            sa.Enum(
                "AdminOneUseCode",
                "AdminMultiUseCode",
                "CompanyOneUseCode",
                "CompanyMultiUseCode",
                "CompanyISTID",
                name="CodeFlowEnum",
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activities", "code_work_flow")
    # ### end Alembic commands ###
