"""empty message

Revision ID: f26c97884a83
Revises: 
Create Date: 2022-03-06 20:37:29.774603

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f26c97884a83"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activities", "code_work_flow")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activities",
        sa.Column(
            "code_work_flow",
            postgresql.ENUM(
                "AdminCode", "CompanyCode", "CompanyISTID", name="CodeFlowEnum"
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
